export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const SET_CASE_DATA = 'SET_CASE_DATA';
export const SET_SUMMARY_DATA = 'SET_SUMMARY_DATA';

export const SAVE_CASE_FILTER_PAYLOAD = 'SAVE_CASE_FILTER_PAYLOAD';
export const CLEAR_CASE_FILTER_PAYLOAD = "CLEAR_CASE_FILTER_PAYLOAD";

