// actionTypes.js
export const SET_REPORT_RESULTS = 'SET_REPORT_RESULTS';

export const SAVE_REPORT_FILTER_PAYLOAD = 'SAVE_REPORT_FILTER_PAYLOAD';
export const CLEAR_REPORT_FILTER_PAYLOAD = "CLEAR_REPORT_FILTER_PAYLOAD";
